### ISSUE TITLE
5주차 회의

### ISSUE THREAD

**Issue by hyunjunyong** [hyunjunyong/middle-location-pg#1]
## 이번주 토요일 저녁

1. 선호도가 있는 장소 프로그램 / 선호도에 대한 데이터 적용 가능성 (   데이터 가지고 추천 및 기존 좋아요 기록 )/선호도 - 준용&휘빈
2. 교통이 편한 곳 (버스가 한번에 모이는 곳 ,환승 x, 지하철 모이는 장소)/대중교통 - 은지
3. api가 있으면 찾고 등으로 절차 만들어 데이터 확보 알아보기 / 후보 리스트 올리기 가능성 /데이터 적용 - 주희
4. 추천시스템 알고리즘,  웹크롤링 툴 등 자세하기 정하기 - 휘빈&준용

***다 찾은다음에 각자 한번씩 시도해보기 안되면 단톡에서 공유하고 같이 해봅시당***

---

### 추천

 

- 처음 무작위 → 이후에는 항목별로
- 관광지
- 음식점
- 장소 추천 → 1. 중간위치 2. (중간위치 애매하면)가까운 시내 추천 3. ??
    - 장소에서 갈 곳 추천 → (항목별)1. 카페 2. 음식점  3. ??? 등

**Comment by y00eunji** [comment]
### 우선순위

1. 웹 크롤링 → 장소 추천 
2. 웹 페이지  → 부트스트랩
3. 주소 api 입력 → 주소 입력시 위치 찍어주는 것 (DB)
4. 중간 위치 찾아주기 *** 
5. 두번째 추천 위치 
6. 주변 음식점 및 카페 추천 
7. 가는 길 찾기 (대중교통)

---

### 선호도

- 네이버, 카카오 리뷰 크롤링 → 파이썬사용예정
- 첫 사용자만 크롤링 통한 추천
- 밥,디저트, 관광지,쇼핑
